<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>1701,1702</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wolverine.AzureFunctions.Domain\Wolverine.AzureFunctions.Domain.csproj" />
    <ProjectReference Include="..\Wolverine.AzureFunctions.Application\Wolverine.AzureFunctions.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />
  </ItemGroup>
  </Project>