using Intent.RoslynWeaver.Attributes;
using Serilog;
using Serilog.Events;
using Wolverine;
using Wolverine.CQRS.TestApplication.Api.Configuration;
using Wolverine.CQRS.TestApplication.Api.Filters;
using Wolverine.CQRS.TestApplication.Api.Logging;
using Wolverine.CQRS.TestApplication.Application;
using Wolverine.CQRS.TestApplication.Application.Common.Behaviours;
using Wolverine.CQRS.TestApplication.Application.Common.Interfaces;
using Wolverine.CQRS.TestApplication.Infrastructure;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.AspNetCore.Program", Version = "1.0")]

namespace Wolverine.CQRS.TestApplication.Api
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using var logger = new LoggerConfiguration()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateBootstrapLogger();

            try
            {
                var builder = WebApplication.CreateBuilder(args);

                builder.Services.AddControllers(
                    opt =>
                    {
                        opt.Filters.Add<ExceptionFilter>();
                    });
                builder.Services.AddApplication(builder.Configuration);
                builder.Services.ConfigureApplicationSecurity(builder.Configuration);
                builder.Services.ConfigureHealthChecks(builder.Configuration);
                builder.Services.ConfigureProblemDetails();
                builder.Services.ConfigureApiVersioning();
                builder.Services.AddInfrastructure(builder.Configuration);
                builder.Services.ConfigureSwagger(builder.Configuration);

                builder.Host.UseWolverine(opts =>
                {
                    // Assembly anchor: typeof(ICommand) is generated by this module and lives in the Application project.
                    // Using ICommand rather than a handler class because ICommand is always present once Commands exist,
                    // whereas a specific handler class (e.g. CreateItemCommandHandler) would be a user type the FactoryExtension
                    // cannot reference directly. The reference app used typeof(CreateItemCommandHandler) for hand-crafting;
                    // ICommand is the stable, generated anchor.
                    opts.Discovery.IncludeAssembly(typeof(ICommand).Assembly);

                    // Apply middleware to all Commands and Queries only (not domain events / other messages)
                    opts.Policies.AddMiddleware<AuthorizationMiddleware>(chain =>
                    typeof(ICommand).IsAssignableFrom(chain.MessageType) ||
                    typeof(IQuery).IsAssignableFrom(chain.MessageType));
                    opts.Policies.AddMiddleware<ValidationMiddleware>(chain =>
                    typeof(ICommand).IsAssignableFrom(chain.MessageType) ||
                    typeof(IQuery).IsAssignableFrom(chain.MessageType));
                    opts.Policies.AddMiddleware<LoggingMiddleware>(chain =>
                    typeof(ICommand).IsAssignableFrom(chain.MessageType) ||
                    typeof(IQuery).IsAssignableFrom(chain.MessageType));
                    opts.Policies.AddMiddleware<PerformanceMiddleware>(chain =>
                    typeof(ICommand).IsAssignableFrom(chain.MessageType) ||
                    typeof(IQuery).IsAssignableFrom(chain.MessageType));
                    opts.Policies.AddMiddleware<UnhandledExceptionMiddleware>(chain =>
                    typeof(ICommand).IsAssignableFrom(chain.MessageType) ||
                    typeof(IQuery).IsAssignableFrom(chain.MessageType));
                    opts.Policies.AddMiddleware<UnitOfWorkMiddleware>(chain =>
                    typeof(ICommand).IsAssignableFrom(chain.MessageType)); // Commands only — UoW on reads is wasteful
                });

                builder.Host.UseSerilog((context, services, configuration) => configuration
                    .ReadFrom.Configuration(context.Configuration)
                    .ReadFrom.Services(services)
                    .Destructure.With(new BoundedLoggingDestructuringPolicy()));

                var app = builder.Build();

                // Configure the HTTP request pipeline.
                app.UseSerilogRequestLogging();
                app.UseExceptionHandler();
                app.UseHttpsRedirection();
                app.UseRouting();
                app.UseAuthentication();
                app.UseAuthorization();
                app.MapDefaultHealthChecks();
                app.MapControllers();
                app.UseSwashbuckle(builder.Configuration);

                logger.Write(LogEventLevel.Information, "Starting web host");

                app.Run();
            }
            catch (HostAbortedException)
            {
                // Excluding HostAbortedException from being logged, as this is an expected
                // exception when working with EF Core migrations (as per the .NET team on the below link)
                // https://github.com/dotnet/efcore/issues/29809#issuecomment-1344101370
            }
            catch (Exception ex)
            {
                logger.Write(LogEventLevel.Fatal, ex, "Unhandled exception");
            }
        }
    }
}
