trigger:
  batch: true
  branches:
    include:
    - master

stages:
  - stage:
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'

        steps:

          - checkout: self
            persistCredentials: true
    
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            condition: succeeded()
            env:
              DOTNET_NOLOGO: 'true'
            inputs:
              command: 'build'
              projects: '**/*.sln'
              arguments: '--nologo'
