using System;
using System.Collections.Generic;
using System.Linq;
using Intent.Engine;
using Intent.Metadata.Models;
using Intent.Modules.Common;
using Intent.Modules.Common.FileBuilders.MarkdownFileBuilder;
using Intent.Modules.Common.Templates;
using Intent.RoslynWeaver.Attributes;
using Intent.Templates;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.ModuleBuilder.ProjectItemTemplate.Partial", Version = "1.0")]

namespace Intent.Modules.Blazor.Templates.Templates.AI.BlazorAppMenuSkill
{
    [IntentManaged(Mode.Merge, Signature = Mode.Fully)]
    public class BlazorAppMenuSkillTemplate : MarkdownBaseTemplate<object>, IMarkdownFileBuilderTemplate
    {
        [IntentManaged(Mode.Fully)]
        public const string TemplateId = "Intent.Blazor.Templates.AI.BlazorAppMenuSkillTemplate";

        [IntentManaged(Mode.Fully, Body = Mode.Ignore)]
        public BlazorAppMenuSkillTemplate(IOutputTarget outputTarget, object model = null) : base(TemplateId, outputTarget, model)
        {
            WithContentHashing = true;
            MarkdownFile = new MarkdownFile($"SKILL", "md", "blazor-app-menu")
                .FromMarkdown("""
                    ---
                    name: blazor-app-menu
                    description: Populates MainLayoutHeader.razor, MainLayoutSider.razor, MainLayoutFooter.razor, the Profile menu file (e.g. AppUserMenu.razor), and (if present) ManageLayout.razor's nav block, either from a natural-language description of the app's menu structure or from modeled Navigation Target Ends (Layout Placement -> Regions), gating individual items by authentication/roles/policy only when the project actually has the Authentication module installed. Use when asked to add, change, or regenerate navigation/menu items, sider links, header links, or the profile/account menu in a Blazor project using MainLayout/MainLayoutHeader/MainLayoutSider/MainLayoutFooter/Profile-Menu, and whenever a Navigation Target End on MainLayout was added, changed, or removed.
                    paths:
                    ---

                    ## Purpose

                    Every Blazor project generated by this solution's Intent Architect module has a `MainLayout.razor` that is intentionally thin — it just composes `<MainLayoutHeader/>`, `<MainLayoutSider/>`, `@Body`, `<MainLayoutFooter/>`. The actual menu content lives as **literal, hand-authored markup** inside those component files (and, for Auth projects, is duplicated into `ManageLayout.razor`'s `<aside>` for the static-SSR Account area). There is deliberately **no shared nav-item data model**.

                    Each of `MainLayoutHeader.razor`, `MainLayoutSider.razor`, `MainLayoutFooter.razor`, and (when modeled) the Profile menu file is scaffolded exactly once by Software Factory (`OverwriteDisabled`) from the `Navigation Target End`s assigned to its region — after that first generation, keeping their literal markup in sync with navigation changes is entirely this skill's job.

                    This skill turns a menu description — either free-text prose, or the `Navigation Target End`/`Regions` context Software Factory attaches to each scaffolded file — into that literal markup, correctly gated by `<AuthorizeView>` when (and only when) the target project actually has authentication.

                    ---

                    ## MANDATORY: Read Before Making Any Change

                    STOP — you MUST read all of the following before writing anything:

                    **Samples** (in the SAME folder as this SKILL.md):
                    1. `app-sider-noauth-sample.razor` — Sider with no auth gating
                    2. `app-sider-auth-sample.razor` — Sider with a mix of gated and ungated items
                    3. `app-header-auth-sample.razor` — Header with a gated nav item plus the fixed Login/Register-vs-AppUserMenu split
                    4. `manage-layout-nav-auth-sample.razor` — the required literal duplicate for the static-SSR Account area
                    5. `app-user-menu-auth-sample.razor` — the real Auth Profile menu (modeled Profile-region items plus the fixed Logout action), relevant whenever you're populating that file per Step 7

                    **Target project files:**
                    1. `Components/Layout/MainLayoutHeader.razor` (+ `.razor.cs`)
                    2. `Components/Layout/MainLayoutSider.razor` (+ `.razor.cs`)
                    3. `Components/Layout/MainLayoutFooter.razor` (+ `.razor.cs`)
                    4. The Profile menu file — only exists if MainLayout has a modeled Profile Menu child element; commonly named `AppUserMenu.razor` but the actual filename is `{Layout name}{Profile Menu element name}.razor`. Path varies: `Components/Layout/` (NoAuth, or WASM NoAuth after path unification), `Components/Account/Shared/` (Server Auth), or `Layout/` in the `.Client` project (WASM Auth — kept separate from `Components/Layout` on purpose, see "WASM Auth specifics" below)
                    5. `Components/Account/Shared/ManageLayout.razor` — only exists in Auth projects; if absent, skip step 6 entirely
                    6. `Program.cs` (and, for a hosted WASM Auth project, the host project's `Program.cs` too)

                    Do not proceed with a partial read. If any of items 2–4 above are missing do NOT create them — this skill assumes that shape already exists; it does not create it. Not all of the target files will be present for every solution - some may be omitted.

                    ---

                    ## Step 1 — Detect the Project's Shape

                    Before touching any markup, determine two independent facts by inspecting `Program.cs`:

                    | Fact | How to tell | Why it matters |
                    |---|---|---|
                    | **Auth capability** | Does `Program.cs` call `AddAuthorizationCore()` / `AddAuthorization()` **and** `AddCascadingAuthenticationState()`? | If NO: this is a **NoAuth** project. `<AuthorizeView>` has no cascading auth state to consume and **must never be introduced**. If YES: this is an **Auth** project and `<AuthorizeView>` is safe anywhere. |
                    | **Hosting model** | Is there a separate `.Client` project referenced by a host project (`ProjectReference` + `AddInteractiveWebAssemblyComponents`), or is it a single project? | Hosted WASM Auth has real account/menu content split across host (static-SSR) and `.Client` (interactive) — see "WASM Auth specifics" below. Blazor Server and standalone WASM don't have this split. |

                    Never infer auth capability from the project's *name* (e.g. don't assume "NoAuth" in a folder name means no auth, or vice versa) — always verify against `Program.cs`, since this skill may be run against a renamed or copied project.

                    ---

                    ## Step 2 — Parse the Menu Description Into Items

                    The context you're given will be prose, not a formal schema, along the lines of:

                    > "The sider menu consists of the following:
                    > - a navigation link to the product list page with route `/product-list`
                    > - a navigation link to the order list page with route `/order-list` which requires roles `Admin` or `Write`"

                    For each described link, extract:

                    | Field | How to extract | Default if unstated |
                    |---|---|---|
                    | **Label** | The page/entity name mentioned (title-case it: "product list" → "Product List") | Required — ask if truly ambiguous |
                    | **Href** | The literal route given (e.g. `` `/product-list` ``) | Required |
                    | **Section** | Explicit mention of "header", "sider"/"side menu", "footer", or "profile"/"account menu" | **Sider** |
                    | **Icon** | Only if explicitly described (e.g. "with a home icon") — map to the closest `Icons.Material.Filled.*` member | None — omit the `Icon` attribute entirely rather than guessing |
                    | **Authorization** | Phrases like "requires roles `X` or `Y`", "requires policy `X`", "for logged-in users only" / "requires authentication" | None (item renders unconditionally) |

                    **Model-derived invocation:** when this skill runs because a `Navigation Target End` changed rather than because of a typed request, the item list isn't prose you're handed directly — it's the AI Context Software Factory attached to each scaffolded file (`MainLayoutHeader.razor`, `MainLayoutSider.razor`, `MainLayoutFooter.razor`, the Profile menu file), in the exact same "a navigation link to the X with route 'Y' [with required role(s)/policies...]" phrasing as the example above. Parse it with the identical rules in the table above — the `Regions` value on each `Navigation Target End` is what already routed that item's context to the right file.

                    Authorization phrase mapping:
                    - "requires roles `A` or `B`" → gate with `Roles="A,B"` (comma-joined, see Step 4 — `AuthorizeView.Roles` is a single comma-delimited string, not a collection)
                    - "requires policy `X`" → gate with `Policy="X"`
                    - "for logged-in users" / "requires authentication" / "requires login" with no roles/policy → gate with a bare `<AuthorizeView>` (no `Roles`/`Policy` attribute — matches any authenticated user)
                    - No authorization language at all → do not wrap the item in anything

                    If the target project is **NoAuth** (per Step 1) and the context nonetheless describes a role/policy/login requirement for an item: render the item **unconditionally** anyway (there is no auth infrastructure to gate it with) and say so plainly in your response — do not silently drop the item, and do not add `AddAuthorizationCore`/`AddCascadingAuthenticationState` to `Program.cs` to make the gating "work". That is a much bigger change than a menu edit and is out of scope for this skill.

                    ---

                    ## Step 3 — Populate `MainLayoutSider.razor`

                    Follow `app-sider-noauth-sample.razor` or `app-sider-auth-sample.razor` depending on Step 1's result.

                    Rules:
                    - Preserve the outer `<MudDrawer Open="DrawerOpen" OpenChanged="DrawerOpenChanged" ...>` wrapper exactly — do not rename these parameters or change the binding shape; `MainLayout.razor` depends on them.
                    - Every item is a plain `<MudNavLink Href="..." [Icon="..."]>Label</MudNavLink>` inside a single `<MudNavMenu>`.
                    - The root/home link should get `Match="NavLinkMatch.All"` (so it doesn't stay highlighted on every route); other links should omit `Match` and take MudBlazor's default (`Prefix`).
                    - **Auth project, gated item**: wrap only that `<MudNavLink>` in `<AuthorizeView Roles="..."> <Authorized> ... </Authorized> </AuthorizeView>` (or `Policy="..."`, or bare `<AuthorizeView>` for "any authenticated user"). Do **not** add a `<NotAuthorized>` fragment — the item should render nothing when the viewer doesn't qualify, not an alternate message.
                    - **NoAuth project**: never emit `<AuthorizeView>` here at all, regardless of what the context says (see Step 2's fallback).
                    - Preserve any items already present in the file that the new context doesn't mention, unless the user's instructions say to replace the whole menu — treat this as an additive edit by default.

                    ### Region source-of-truth and "mandatory" sync (CRITICAL)

                    This skill must be **region-scoped**: a nav item may only be generated into a given region/menu when the input context explicitly places it there.

                    Rules:

                    - Treat each region/menu (`Header`, `Sider`, `Footer`, `Profile`) as a separate, independent output.
                    - Only generate/ensure items for **this region** (Sider) when the context places them in Sider (explicitly) or omits a section (defaulting to Sider per Step 2).
                    - Never infer region placement from the existing code (e.g. "the header already has links") and never mirror items across regions as a convention.
                    - Only prevent duplicates **within the same region/menu**; the same route may legitimately appear in multiple regions if (and only if) the context explicitly says so.

                    ---

                    ## Step 4 — Populate `MainLayoutHeader.razor`

                    Follow `app-header-auth-sample.razor` for Auth projects. Two independent concerns live in this file — do not conflate them:

                    1. **The user-menu slot** (Auth projects only): `<AuthorizeView><Authorized>...</Authorized><NotAuthorized>` Login/Register buttons `</NotAuthorized></AuthorizeView>`. The `<Authorized>` fragment contains the Profile menu component reference (commonly `<AppUserMenu />`) **if and only if** the Profile menu (Step 7) currently has at least one qualifying item — if it has none, `<Authorized>` renders nothing extra here. Software Factory only inserts this reference automatically the first time the Profile menu element is modeled; every navigation change afterward that takes the Profile menu from empty to non-empty (or back) is yours to reflect here by hand. The Login/Register-vs-Authorized split itself is permanent scaffolding, not something the menu context drives — never remove it. NoAuth projects instead have a bare, unconditional slot that follows the same has-qualifying-items rule, with no Authorized/NotAuthorized split.
                    2. **Any Header-placed nav items** the context describes: render as `<MudButton Href="..." Color="Color.Inherit">Label</MudButton>` (MudAppBar is not a `MudNavMenu`, so `MudNavLink` doesn't fit here), positioned between the brand button and `<MudSpacer />`. Gate exactly like a Sider item (Step 3's `AuthorizeView` rules), in a NoAuth project never gate at all.

                    Preserve the drawer-toggle `MudIconButton`, the brand `MudButton`, `MudSpacer`, and `ThemeToggle` exactly as they are — only add to what's between the brand and the user-menu slot.

                    ### Region source-of-truth and "mandatory" sync (CRITICAL)

                    Only add/ensure header nav items that the context explicitly assigns to the Header section.

                    Rules:

                    - If the context does not mention any header items, do not add new header navigation buttons.
                    - Do not mirror Sider items into the Header by convention.
                    - Only prevent duplicates within the Header itself.

                    ---

                    ## Step 5 — Populate `MainLayoutFooter.razor`

                    Only touch this file if the context explicitly describes footer content. Otherwise leave it as the empty placeholder — do not invent footer content. If footer items are described, apply the same per-item rules as Step 3 (plain links, `AuthorizeView`-gated only in Auth projects, only for items with a stated requirement), rendered as plain `<a>`/`MudLink` elements rather than `MudNavLink` (footers typically aren't route-highlighted navigation).

                    ### Region source-of-truth and "mandatory" sync (CRITICAL)

                    Only add/ensure footer items that the context explicitly assigns to the Footer section.

                    Rules:

                    - If the context does not mention any footer items, leave the footer unchanged.
                    - Do not mirror Sider/Header items into the Footer by convention.
                    - Only prevent duplicates within the Footer itself.

                    ---

                    ## Step 6 — Sync `ManageLayout.razor`'s Nav Block (Auth projects only)

                    If `Components/Account/Shared/ManageLayout.razor` exists (it won't in a NoAuth project — skip this step there), it contains an `<aside class="ux-account-nav-drawer">` block that must carry the **exact same items and gating** as `MainLayoutSider.razor`'s `<MudNavMenu>` — see `manage-layout-nav-auth-sample.razor`. This is a literal, independent copy (there is no shared data source), so every change you make to `MainLayoutSider.razor`'s menu items must be mirrored here by hand. Do not skip this file — a menu item added only to `MainLayoutSider` will silently be missing from the Account/Manage area's drawer.

                    ---

                    ## Step 7 — Populate the Profile Menu file (e.g. `AppUserMenu.razor`)

                    This file only exists when `MainLayout` has a modeled **Profile Menu** child element (visible alongside Header/Sider/Footer in the User Interface designer) — if there is none, there is no Profile menu and this step doesn't apply. When present, it's scaffolded exactly like Steps 3-5: a Razor file (commonly `AppUserMenu.razor`, colocated with the other layout files per the path rules in "MANDATORY" above) generated once with `OverwriteDisabled` — from then on you own its contents.

                    This menu is populated from `Navigation Target End`s whose `Layout Placement` -> `Regions` is set to `Profile`. It's primarily meant for profile/account-related pages (e.g. "My Profile", "Settings"), but it can hold any navigable page the context/model assigns to it — treat it exactly like Step 3's Sider population:

                    - Each qualifying item renders inside `<UserMenu><ChildContent>...</ChildContent></UserMenu>` (preserve the scaffolded `<Trigger>` icon exactly) as `<a class="ux-user-menu-item" href="...">` + an icon + the label — see `app-user-menu-auth-sample.razor` for the exact shape.
                    - Apply the same Label/Href/Icon/Authorization extraction as Step 2, and the same Auth-vs-NoAuth `AuthorizeView` gating rules as Step 3.
                    - If the Profile menu currently has zero qualifying items, leave the file as its scaffolded placeholder ("Add menu items") — do not invent content.

                    **Auth projects only — the fixed Logout action:** Logout is not a navigable page, so it's never sourced from a `Navigation Target End`. It is permanent scaffolding — the same kind as the Header's Login/Register split (Step 4) — and must always be present in an Auth project's Profile menu, appended after any modeled items: a `<form class="ux-user-menu-logout-form" action="Account/Logout" method="post">` containing `<AntiforgeryToken />`, a hidden `returnUrl` input, and a submit `<button>` with the Logout label/icon (see `app-user-menu-auth-sample.razor`). Never remove it, never gate it with `AuthorizeView`, and never replace the POST-form with an `OnClick` handler or client-side auth call.

                    ### Region source-of-truth and "mandatory" sync (CRITICAL)

                    Only add/ensure items that the context/model explicitly assigns to the Profile region.

                    Rules:

                    - If nothing is assigned to Profile, leave the file as its placeholder (Auth projects still get the fixed Logout block).
                    - Do not mirror Sider/Header/Footer items into the Profile menu by convention.
                    - Only prevent duplicates within the Profile menu itself.

                    **WASM Auth specifics**: in a hosted WASM Auth project, this file exists in **two places** — the host project's `Components/Account/Shared/AppUserMenu.razor` (static-SSR, used by `ManageLayout`) and the `.Client` project's `Layout/AppUserMenu.razor` (interactive, used by `MainLayout`/`MainLayoutHeader`). Both must stay in sync with each other, including the modeled items. The `.Client` copy's links/forms must remain plain relative URLs (`Account/Manage`, `Account/Logout`, etc.) — never a client-side/SPA-style auth call — because the WASM client's `AuthenticationStateProvider` only re-evaluates on a full page navigation; anything else silently fails to update the menu after login/logout.

                    ---

                    ## Forbidden

                    - Reintroducing a shared nav-item model (`NavItem` record, `AppNav` static class, or any `Items` parameter feeding a generic loop) — every menu surface is literal markup by design.
                    - Adding `<AuthorizeView>`, `AddAuthorizationCore()`, or `AddCascadingAuthenticationState()` to a project that doesn't already have them, in order to make a described role/policy requirement "work".
                    - Adding a `<NotAuthorized>` fragment to a gated **nav item** (Sider/Header/Footer link) — items should disappear, not show a fallback message. (The fixed Login/Register `<NotAuthorized>` on the user-menu slot in `MainLayoutHeader` is the one deliberate exception, and it isn't something you add — it already exists.)
                    - Passing `Roles` as anything other than a single comma-delimited string to `AuthorizeView` (it is not a `string[]` parameter).
                    - Editing `MainLayoutSider.razor` without mirroring the change into `ManageLayout.razor` in an Auth project (Step 6).
                    - Replacing the WASM `.Client` `AppUserMenu`'s plain link/POST-form pattern with a client-side auth call.
                    - Inventing routes, roles, or policies that weren't in the given context.
                    - Removing existing menu items the new context doesn't mention (treat as additive unless told otherwise).
                    - Removing the fixed Logout block from an Auth project's Profile menu, or gating it with `AuthorizeView`.
                    - Adding or removing the header's Profile-menu component reference out of step with whether the Profile menu actually has qualifying items.
                    - Assigning items to the Profile region by convention/mirroring rather than because the context/model explicitly placed them there.

                    ---

                    ## Definition of Done

                    - [ ] `Program.cs` was checked to confirm Auth vs NoAuth and hosting model before any edit was made
                    - [ ] Every described item was mapped to Label/Href/Section/Icon/Authorization per Step 2's table
                    - [ ] `MainLayoutSider.razor`'s `MudDrawer` wrapper (`DrawerOpen`/`DrawerOpenChanged`) was left unchanged
                    - [ ] Gated Sider/Header/Footer items use `<AuthorizeView>` with only an `<Authorized>` fragment — no `<NotAuthorized>`
                    - [ ] `AuthorizeView.Roles` is a comma-joined string, not an array literal
                    - [ ] No `AuthorizeView`/auth service registration was added to a NoAuth project, even if the context implied a role requirement
                    - [ ] `MainLayoutHeader.razor`'s fixed Login/Register-vs-AppUserMenu split (Auth) or unconditional `<AppUserMenu/>` (NoAuth) was preserved untouched
                    - [ ] If `ManageLayout.razor` exists, its `<aside>` nav block was updated to match `AppSider.razor` exactly
                    - [ ] The Profile menu file (if modeled) reflects exactly the items assigned to the Profile region, plus the fixed Logout block in Auth projects, and nothing else
                    - [ ] `MainLayoutHeader.razor`'s Profile-menu component reference is present iff the Profile menu currently has at least one qualifying item
                    - [ ] If editing a hosted WASM Auth project's `AppUserMenu`, both the host and `.Client` copies were kept in sync, and the `.Client` copy still uses plain relative links/POST forms, not a client-side auth call
                    - [ ] No shared nav-item data model (`NavItem`/`AppNav`) was reintroduced
                    - [ ] Existing menu items not mentioned in the new context were preserved

                    """);
        }

        [IntentManaged(Mode.Fully)]
        public override IMarkdownFile MarkdownFile { get; }

        [IntentManaged(Mode.Fully)]
        public override ITemplateFileConfig GetTemplateFileConfig() => MarkdownFile.GetConfig();

    }
}
