// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.ServiceProxies.Templates.ServiceProxiesConfiguration
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.Application.Contracts.Clients.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ServiceProxiesConfigurationTemplate : CSharpTemplateBase<IList<Intent.Modelers.Types.ServiceProxies.Api.ServiceProxyModel>>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing Microsoft.Extensions.Configuration;\r\nusing Microsoft.Extensions.DependencyInjection;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public static class ");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public static void AddServiceProxies(this IServiceCollection services, IConfiguration configuration)\r\n        {\r\n            services.AddAccessTokenManagement(options =>\r\n            {\r\n                configuration.GetSection(\"IdentityClients\").Bind(options.Client.Clients);\r\n            }).ConfigureBackchannelHttpClient();\r\n\r\n");
            
            #line 28 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"

    foreach (var proxy in Model)
    {

            
            #line default
            #line hidden
            this.Write("            services.AddHttpClient<");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetServiceContractName(proxy)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetServiceProxyClientName(proxy)));
            
            #line default
            #line hidden
            this.Write(">(http =>\r\n            {\r\n                http.BaseAddress = configuration.GetValue<Uri>(\"");
            
            #line 34 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetConfigKey(proxy, "Uri")));
            
            #line default
            #line hidden
            this.Write("\");\r\n                http.Timeout = configuration.GetValue<TimeSpan?>(\"");
            
            #line 35 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetConfigKey(proxy, "Timeout")));
            
            #line default
            #line hidden
            this.Write("\") ?? TimeSpan.FromSeconds(100);\r\n            })");
            
            #line 36 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMessageHandlers(proxy)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 37 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.ServiceProxies\Templates\ServiceProxiesConfiguration\ServiceProxiesConfigurationTemplate.tt"
        
    }

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
