using System.Linq;
using Intent.Engine;
using Intent.Modules.Common;
using Intent.Modules.Common.CSharp.AppStartup;
using Intent.Modules.Common.CSharp.Builder;
using Intent.Modules.Common.CSharp.Templates;
using Intent.Modules.Common.Plugins;
using Intent.Modules.Constants;
using Intent.Plugins.FactoryExtensions;
using Intent.RoslynWeaver.Attributes;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.ModuleBuilder.Templates.FactoryExtension", Version = "1.0")]

namespace Intent.Modules.Application.Wolverine.FactoryExtensions
{
    [IntentManaged(Mode.Fully, Body = Mode.Merge)]
    public class WolverineRegistrationFactoryExtension : FactoryExtensionBase
    {
        public override string Id => "Intent.Application.Wolverine.WolverineRegistrationFactoryExtension";

        [IntentManaged(Mode.Ignore)]
        public override int Order => 0;

        /// <summary>
        /// This is an example override which would extend the
        /// <see cref="ExecutionLifeCycleSteps.AfterTemplateRegistrations"/> phase of the Software Factory execution.
        /// See <see cref="FactoryExtensionBase"/> for all available overrides.
        /// </summary>
        /// <remarks>
        /// It is safe to update or delete this method.
        /// </remarks>
        protected override void OnAfterTemplateRegistrations(IApplication application)
        {
            var programTemplate = application.FindTemplateInstance<IProgramTemplate>("App.Program");
            var appDiTemplate = application.FindTemplateInstance<ICSharpFileBuilderTemplate>(TemplateRoles.Application.DependencyInjection);

            if (programTemplate != null)
            {
                programTemplate.AddNugetDependency(NugetPackages.WolverineFx(programTemplate.OutputTarget));

                programTemplate.CSharpFile.OnBuild(file =>
                {
                    file.AddUsing("Wolverine");

                    var commandInterfaceType = programTemplate.GetTypeName("Intent.Application.Wolverine.CommandInterface");
                    var queryInterfaceType = programTemplate.GetTypeName("Intent.Application.Wolverine.QueryInterface");

                    var authMiddleware = programTemplate.GetTypeName("Intent.Application.Wolverine.AuthorizationMiddleware");
                    var valMiddleware = programTemplate.GetTypeName("Intent.Application.Wolverine.ValidationMiddleware");
                    var logMiddleware = programTemplate.GetTypeName("Intent.Application.Wolverine.LoggingMiddleware");
                    var perfMiddleware = programTemplate.GetTypeName("Intent.Application.Wolverine.PerformanceMiddleware");
                    var errMiddleware = programTemplate.GetTypeName("Intent.Application.Wolverine.UnhandledExceptionMiddleware");
                    var uowMiddleware = programTemplate.GetTypeName("Intent.Application.Wolverine.UnitOfWorkMiddleware");

                    programTemplate.ProgramFile.ConfigureHostBuilderChainStatement("UseWolverine", new[] { "opts" },
                        (lambdaBlock, parameters) =>
                        {
                            var opts = parameters[0];
                            lambdaBlock.Statements.Clear();

                            lambdaBlock.AddStatement($"// Assembly anchor: typeof({commandInterfaceType}) is generated by this module and lives in the Application project.");
                            lambdaBlock.AddStatement($"// Using {commandInterfaceType} rather than a handler class because {commandInterfaceType} is always present once Commands exist,");
                            lambdaBlock.AddStatement($"// whereas a specific handler class (e.g. CreateItemCommandHandler) would be a user type the FactoryExtension");
                            lambdaBlock.AddStatement($"// cannot reference directly. The reference app used typeof(CreateItemCommandHandler) for hand-crafting;");
                            lambdaBlock.AddStatement($"// {commandInterfaceType} is the stable, generated anchor.");
                            lambdaBlock.AddStatement($"{opts}.Discovery.IncludeAssembly(typeof({commandInterfaceType}).Assembly);");
                            lambdaBlock.AddStatement("");
                            lambdaBlock.AddStatement($"// Apply middleware to all Commands and Queries only (not domain events / other messages)");
                            lambdaBlock.AddStatement($"{opts}.Policies.AddMiddleware<{authMiddleware}>(chain =>");
                            lambdaBlock.AddStatement($"    typeof({commandInterfaceType}).IsAssignableFrom(chain.MessageType) ||");
                            lambdaBlock.AddStatement($"    typeof({queryInterfaceType}).IsAssignableFrom(chain.MessageType));");
                            lambdaBlock.AddStatement($"{opts}.Policies.AddMiddleware<{valMiddleware}>(chain =>");
                            lambdaBlock.AddStatement($"    typeof({commandInterfaceType}).IsAssignableFrom(chain.MessageType) ||");
                            lambdaBlock.AddStatement($"    typeof({queryInterfaceType}).IsAssignableFrom(chain.MessageType));");
                            lambdaBlock.AddStatement($"{opts}.Policies.AddMiddleware<{logMiddleware}>(chain =>");
                            lambdaBlock.AddStatement($"    typeof({commandInterfaceType}).IsAssignableFrom(chain.MessageType) ||");
                            lambdaBlock.AddStatement($"    typeof({queryInterfaceType}).IsAssignableFrom(chain.MessageType));");
                            lambdaBlock.AddStatement($"{opts}.Policies.AddMiddleware<{perfMiddleware}>(chain =>");
                            lambdaBlock.AddStatement($"    typeof({commandInterfaceType}).IsAssignableFrom(chain.MessageType) ||");
                            lambdaBlock.AddStatement($"    typeof({queryInterfaceType}).IsAssignableFrom(chain.MessageType));");
                            lambdaBlock.AddStatement($"{opts}.Policies.AddMiddleware<{errMiddleware}>(chain =>");
                            lambdaBlock.AddStatement($"    typeof({commandInterfaceType}).IsAssignableFrom(chain.MessageType) ||");
                            lambdaBlock.AddStatement($"    typeof({queryInterfaceType}).IsAssignableFrom(chain.MessageType));");
                            lambdaBlock.AddStatement($"{opts}.Policies.AddMiddleware<{uowMiddleware}>(chain =>");
                            lambdaBlock.AddStatement($"    typeof({commandInterfaceType}).IsAssignableFrom(chain.MessageType)); // Commands only — UoW on reads is wasteful");
                        });
                });
            }

            if (appDiTemplate != null)
            {
                appDiTemplate.CSharpFile.OnBuild(file =>
                {
                    var @class = file.Classes.First();
                    var method = @class.FindMethod("AddApplication");
                    if (method != null)
                    {
                        var authMiddleware = appDiTemplate.GetTypeName("Intent.Application.Wolverine.AuthorizationMiddleware");
                        var valMiddleware = appDiTemplate.GetTypeName("Intent.Application.Wolverine.ValidationMiddleware");
                        var logMiddleware = appDiTemplate.GetTypeName("Intent.Application.Wolverine.LoggingMiddleware");
                        var perfMiddleware = appDiTemplate.GetTypeName("Intent.Application.Wolverine.PerformanceMiddleware");
                        var errMiddleware = appDiTemplate.GetTypeName("Intent.Application.Wolverine.UnhandledExceptionMiddleware");
                        var uowMiddleware = appDiTemplate.GetTypeName("Intent.Application.Wolverine.UnitOfWorkMiddleware");

                        method.AddStatement($"services.AddTransient<{authMiddleware}>();");
                        method.AddStatement($"services.AddTransient<{valMiddleware}>();");
                        method.AddStatement($"services.AddTransient<{logMiddleware}>();");
                        method.AddStatement($"services.AddTransient<{perfMiddleware}>();");
                        method.AddStatement($"services.AddTransient<{errMiddleware}>();");
                        method.AddStatement($"services.AddTransient<{uowMiddleware}>();");
                    }
                });
            }
        }

        /// <summary>
        /// This is an example override which would extend the
        /// <see cref="ExecutionLifeCycleSteps.BeforeTemplateExecution"/> phase of the Software Factory execution.
        /// See <see cref="FactoryExtensionBase"/> for all available overrides.
        /// </summary>
        /// <remarks>
        /// It is safe to update or delete this method.
        /// </remarks>
        protected override void OnBeforeTemplateExecution(IApplication application)
        {
            // Your custom logic here.
        }
    }
}