// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.EntityFrameworkCore.Templates.DbMigrationsReadMe
{
    using Intent.Modules.Common.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DbMigrationsReadMeTemplate : IntentTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"See https://learn.microsoft.com/ef/core/managing-schemas/migrations for information about
migrations using EF Core. You can perform these commands in the Visual Studio IDE using the
Package Manager Console (View > Other Windows > Package Manager Console) or using the dotnet
Command Line Interface (CLI) instructions. Substitute the {Keywords} below with the appropriate
migration name when executing these commands.

NOTE: When working with DesignTimeDbContextFactory you have to using the CLI. Visual Studio Package Manager Console does not support this feature.
");
            
            #line 11 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraComments()));
            
            #line default
            #line hidden
            this.Write(@"
-------------------------------------------------------------------------------------------------------------------------------------------------------
Create a new migration:
-------------------------------------------------------------------------------------------------------------------------------------------------------
");
            
            #line 15 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
 if(PackageManagerConsoleSupported) {
            
            #line default
            #line hidden
            this.Write("From the Visual Studio Package Manager Console:\r\nAdd-Migration -Name {ChangeName}" +
                    " ");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("-Project \"");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("CLI:\r\ndotnet ef migrations add {ChangeName} ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("--project \"");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write(@"

-------------------------------------------------------------------------------------------------------------------------------------------------------
Remove last migration:
-------------------------------------------------------------------------------------------------------------------------------------------------------
");
            
            #line 26 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
 if(PackageManagerConsoleSupported) {
            
            #line default
            #line hidden
            this.Write("From the Visual Studio Package Manager Console:\r\nRemove-Migration ");
            
            #line 28 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("-Project \"");
            
            #line 28 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 28 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 28 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 30 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("CLI:\r\ndotnet ef migrations remove ");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("--project \"");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write(@"

-------------------------------------------------------------------------------------------------------------------------------------------------------
Update schema to the latest version:
-------------------------------------------------------------------------------------------------------------------------------------------------------
");
            
            #line 37 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
 if(PackageManagerConsoleSupported) {
            
            #line default
            #line hidden
            this.Write("From the Visual Studio Package Manager Console:\r\nUpdate-Database ");
            
            #line 39 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("-Project \"");
            
            #line 39 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 39 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 39 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 41 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("CLI:\r\ndotnet ef database update ");
            
            #line 43 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("--project \"");
            
            #line 43 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 43 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 43 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write(@"

-------------------------------------------------------------------------------------------------------------------------------------------------------
Upgrade/downgrade schema to specific version:
-------------------------------------------------------------------------------------------------------------------------------------------------------
");
            
            #line 48 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
 if(PackageManagerConsoleSupported) {
            
            #line default
            #line hidden
            this.Write("From the Visual Studio Package Manager Console:\r\nUpdate-Database -Migration {Targ" +
                    "et} ");
            
            #line 50 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("-Project \"");
            
            #line 50 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 50 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 50 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 52 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("CLI:\r\ndotnet ef database update {Target} ");
            
            #line 54 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("--project \"");
            
            #line 54 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 54 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 54 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write(@"

-------------------------------------------------------------------------------------------------------------------------------------------------------
Generate a script which detects the current database schema version and updates it to the latest:
-------------------------------------------------------------------------------------------------------------------------------------------------------
");
            
            #line 59 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
 if(PackageManagerConsoleSupported) {
            
            #line default
            #line hidden
            this.Write("From the Visual Studio Package Manager Console:\r\nScript-Migration -Idempotent ");
            
            #line 61 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("-Project \"");
            
            #line 61 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 61 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 61 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 63 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("CLI:\r\ndotnet ef migrations script --idempotent ");
            
            #line 65 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("--project \"");
            
            #line 65 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 65 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 65 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write(@"

-------------------------------------------------------------------------------------------------------------------------------------------------------
Generate a script which upgrades from and to a specific schema version:
-------------------------------------------------------------------------------------------------------------------------------------------------------
");
            
            #line 70 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
 if(PackageManagerConsoleSupported) {
            
            #line default
            #line hidden
            this.Write("From the Visual Studio Package Manager Console:\r\nScript-Migration {Source} {Targe" +
                    "t} ");
            
            #line 72 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("-Project \"");
            
            #line 72 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 72 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVsDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 72 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 74 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("CLI:\r\ndotnet ef migrations script {Source} {Target} ");
            
            #line 76 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliStartupProjectArgument()));
            
            #line default
            #line hidden
            this.Write("--project \"");
            
            #line 76 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MigrationProject));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 76 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCliDbContextArgument()));
            
            #line default
            #line hidden
            
            #line 76 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExtraArguments()));
            
            #line default
            #line hidden
            this.Write(@"

-------------------------------------------------------------------------------------------------------------------------------------------------------
Drop all tables in schema:
-------------------------------------------------------------------------------------------------------------------------------------------------------
DECLARE @SCHEMA AS varchar(max) = '");
            
            #line 81 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.EntityFrameworkCore\Templates\DbMigrationsReadMe\DbMigrationsReadMeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BoundedContextName));
            
            #line default
            #line hidden
            this.Write(@"'
DECLARE @EXECUTE_STATEMENT AS varchar(max) = (SELECT STUFF((SELECT CHAR(13) + CHAR(10) + [Statement] FROM (
    SELECT 'ALTER TABLE ['+@SCHEMA+'].['+[t].[name]+'] DROP CONSTRAINT ['+[fk].[name]+']' AS [Statement] FROM [sys].[foreign_keys] AS [fk] INNER JOIN [sys].[tables] AS [t] ON [t].[object_id] = [fk].[parent_object_id] INNER JOIN [sys].[schemas] AS [s] ON [s].[schema_id] = [t].[schema_id] WHERE [s].[name] = @SCHEMA
    UNION ALL
    SELECT 'DROP TABLE ['+@SCHEMA+'].['+[t].[name]+']' AS [Statement] FROM [sys].[tables] AS [t] INNER JOIN [sys].[schemas] AS [s] ON [s].[schema_id] = [t].[schema_id] WHERE [s].[name] = @SCHEMA
) A FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, ''))
EXECUTE(@EXECUTE_STATEMENT)
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
