using System;
using System.IO;
using System.Linq;
using System.Threading;
using Intent.Engine;
using Intent.Modules.VisualStudio.Projects.Templates.VisualStudioSolution.Merging;
using Microsoft.VisualStudio.SolutionPersistence.Model;
using Microsoft.VisualStudio.SolutionPersistence.Serializer;
using Shouldly;
using Xunit;

namespace Intent.Modules.VisualStudio.Projects.Tests.Templates.SlnxFile
{
    public class SlnxMergerTests
    {
        // ----- Bootstrap / no history -----

        [Fact]
        public void WhenNoExistingFile_ShouldGenerateFreshContentWithoutIds()
        {
            var domainId = Guid.NewGuid();
            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var project = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                project.Id = domainId;
            });

            var result = SlnxMerger.Merge(generated, existing: null, previousOutput: null);

            result.HasDestructiveChanges.ShouldBe(HasDestructiveChanges.False);
            result.Content.ShouldNotContain("Id=");
            var model = Parse(result.Content);
            model.SolutionProjects.Single().FilePath.Replace('\\', '/').ShouldBe("MyApp.Domain/MyApp.Domain.csproj");
        }

        [Fact]
        public void WhenExistingFileButNoPreviousOutput_ShouldFallBackToPathMatching()
        {
            // Real-world case: the .slnx exists (e.g. checked into git) but the local previous-output
            // cache is missing (fresh clone, cleared cache). With no Base to correlate renames against,
            // the merger must degrade gracefully to plain path matching rather than throwing.
            var domainId = Guid.NewGuid();
            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var project = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                project.Id = domainId;
                var api = m.AddFolder("/1 - Api/");
                var newProject = m.AddProject("MyApp.NewThing/MyApp.NewThing.csproj", null, api);
                newProject.Id = Guid.NewGuid();
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput: null);

            result.Content.ShouldNotContain("Id=");
            var model = Parse(result.Content);
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldBe(
                ["MyApp.Domain/MyApp.Domain.csproj", "MyApp.NewThing/MyApp.NewThing.csproj"],
                ignoreOrder: true);
        }

        [Fact]
        public void WhenPreviousOutputHasNoRealIds_MigrationBoundary_ShouldOrphanOldEntryRatherThanThrow()
        {
            // Simulates the one-time transition run immediately after upgrading to this module
            // version: the cached previous template output was generated by the OLD template, which
            // never stamped Ids, so a rename happening in this exact run cannot be correlated. This
            // is a known, documented limitation (not a bug) - from the NEXT run onward, Base will
            // carry real Ids and renames are tracked correctly again.
            var domainId = Guid.NewGuid();
            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder); // no Id - legacy output
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var project = m.AddProject("MyApp.Core/MyApp.Core.csproj", null, folder);
                project.Id = domainId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldBe(
                ["MyApp.Domain/MyApp.Domain.csproj", "MyApp.Core/MyApp.Core.csproj"],
                ignoreOrder: true);
        }

        // ----- Idempotency -----

        [Fact]
        public void WhenNothingChanged_ShouldBeIdempotent()
        {
            var projectId = Guid.NewGuid();
            string Generate() => Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var project = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                project.Id = projectId;
            });

            var firstRun = SlnxMerger.Merge(Generate(), existing: null, previousOutput: null);
            var secondRun = SlnxMerger.Merge(Generate(), existing: firstRun.Content, previousOutput: Generate());

            var model = Parse(secondRun.Content);
            model.SolutionProjects.Count().ShouldBe(1);
            secondRun.Content.ShouldNotContain("Id=");
        }

        // ----- Project-level changes -----

        [Fact]
        public void WhenProjectAdded_ShouldInsertIt()
        {
            var existingId = Guid.NewGuid();
            var newId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = existingId;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = existingId;
                var domain = m.AddFolder("/3 - Domain/");
                var newProject = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, domain);
                newProject.Id = newId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldBe(
                ["MyApp.Api/MyApp.Api.csproj", "MyApp.Domain/MyApp.Domain.csproj"],
                ignoreOrder: true);
        }

        [Fact]
        public void WhenProjectRemovedFromModel_ShouldPreserveExistingEntry()
        {
            var apiId = Guid.NewGuid();
            var domainId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var api = m.AddFolder("/1 - Api/");
                var p1 = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, api);
                p1.Id = apiId;
                var domain = m.AddFolder("/3 - Domain/");
                var p2 = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, domain);
                p2.Id = domainId;
            });

            var existing = Build(m =>
            {
                var api = m.AddFolder("/1 - Api/");
                m.AddProject("MyApp.Api/MyApp.Api.csproj", null, api);
                var domain = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, domain);
            });

            // Domain project removed from the Intent model this run
            var generated = Build(m =>
            {
                var api = m.AddFolder("/1 - Api/");
                var p1 = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, api);
                p1.Id = apiId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldBe(
                ["MyApp.Api/MyApp.Api.csproj", "MyApp.Domain/MyApp.Domain.csproj"],
                ignoreOrder: true);
        }

        [Fact]
        public void WhenProjectRenamedSameFolder_UntouchedByUser_ShouldRenameInPlace()
        {
            var projectId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var p = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                p.Id = projectId;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var p = m.AddProject("MyApp.Core/MyApp.Core.csproj", null, folder);
                p.Id = projectId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Count().ShouldBe(1, "the renamed project must update the existing entry, not orphan it");
            var project = model.SolutionProjects.Single();
            project.FilePath.Replace('\\', '/').ShouldBe("MyApp.Core/MyApp.Core.csproj");
            project.Parent!.Path.ShouldBe("/3 - Domain/");
            result.Content.ShouldNotContain("Id=");
        }

        [Fact]
        public void WhenProjectMovedToDifferentFolder_UntouchedByUser_ShouldReparentInPlace()
        {
            var projectId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var src = m.AddFolder("/src/");
                m.AddFolder("/tests/");
                var p = m.AddProject("src/MyApp.Api/MyApp.Api.csproj", null, src);
                p.Id = projectId;
            });

            var existing = Build(m =>
            {
                var src = m.AddFolder("/src/");
                m.AddFolder("/tests/");
                m.AddProject("src/MyApp.Api/MyApp.Api.csproj", null, src);
            });

            var generated = Build(m =>
            {
                m.AddFolder("/src/");
                var tests = m.AddFolder("/tests/");
                var p = m.AddProject("src/MyApp.Api/MyApp.Api.csproj", null, tests);
                p.Id = projectId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Count().ShouldBe(1);
            var project = model.SolutionProjects.Single();
            project.Parent!.Path.ShouldBe("/tests/");
        }

        [Fact]
        public void WhenProjectRenamedAndMovedSimultaneously_ShouldApplyBoth()
        {
            var projectId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var src = m.AddFolder("/src/");
                m.AddFolder("/tests/");
                var p = m.AddProject("src/MyApp.Api/MyApp.Api.csproj", null, src);
                p.Id = projectId;
            });

            var existing = Build(m =>
            {
                var src = m.AddFolder("/src/");
                m.AddFolder("/tests/");
                m.AddProject("src/MyApp.Api/MyApp.Api.csproj", null, src);
            });

            var generated = Build(m =>
            {
                m.AddFolder("/src/");
                var tests = m.AddFolder("/tests/");
                var p = m.AddProject("tests/MyApp.Api.Tests/MyApp.Api.Tests.csproj", null, tests);
                p.Id = projectId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Count().ShouldBe(1);
            var project = model.SolutionProjects.Single();
            project.FilePath.Replace('\\', '/').ShouldBe("tests/MyApp.Api.Tests/MyApp.Api.Tests.csproj");
            project.Parent!.Path.ShouldBe("/tests/");
        }

        [Fact]
        public void WhenProjectRenamed_ButUserAlreadyEditedThatEntry_ShouldBackOffAndInsertFresh()
        {
            var projectId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var p = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                p.Id = projectId;
            });

            // The user already hand-edited the old entry directly in the file (e.g. renamed it in VS
            // without touching Intent) before this run - the old path is simply gone from Existing.
            var existing = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.HandRenamed/MyApp.HandRenamed.csproj", null, folder);
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var p = m.AddProject("MyApp.Core/MyApp.Core.csproj", null, folder);
                p.Id = projectId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldBe(
                ["MyApp.HandRenamed/MyApp.HandRenamed.csproj", "MyApp.Core/MyApp.Core.csproj"],
                ignoreOrder: true);
        }

        [Fact]
        public void WhenTwoProjectsSwapPaths_ShouldNotCrossWireIdentities()
        {
            var idA = Guid.NewGuid();
            var idB = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var a = m.AddProject("Foo/Foo.csproj", null, folder);
                a.Id = idA;
                var b = m.AddProject("Bar/Bar.csproj", null, folder);
                b.Id = idB;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                m.AddProject("Foo/Foo.csproj", null, folder);
                m.AddProject("Bar/Bar.csproj", null, folder);
            });

            // A renamed from Foo -> Bar, B renamed from Bar -> Foo, in the same run
            var generated = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var a = m.AddProject("Bar/Bar.csproj", null, folder);
                a.Id = idA;
                var b = m.AddProject("Foo/Foo.csproj", null, folder);
                b.Id = idB;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Count().ShouldBe(2, "the swap must not collapse or duplicate either entry");
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldBe(
                ["Foo/Foo.csproj", "Bar/Bar.csproj"],
                ignoreOrder: true);
        }

        // ----- Folder-level changes -----

        [Fact]
        public void WhenFolderRenamed_UntouchedByUser_ShouldRenameInPlaceNoOrphan()
        {
            var folderId = Guid.NewGuid();
            var projectId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                folder.Id = folderId;
                var p = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                p.Id = projectId;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Core/");
                folder.Id = folderId;
                var p = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                p.Id = projectId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Select(f => f.Path).ShouldBe(["/3 - Core/"], "the folder must be renamed in place, not left as an orphan alongside a new one");
            model.SolutionProjects.Single().Parent!.Path.ShouldBe("/3 - Core/");
        }

        [Fact]
        public void WhenFolderReparented_ShouldMoveInPlace()
        {
            var folderId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                m.AddFolder("/A/");
                m.AddFolder("/B/");
                var folder = m.AddFolder("/A/Shared/");
                folder.Id = folderId;
            });

            var existing = Build(m =>
            {
                m.AddFolder("/A/");
                m.AddFolder("/B/");
                m.AddFolder("/A/Shared/");
            });

            var generated = Build(m =>
            {
                m.AddFolder("/A/");
                m.AddFolder("/B/");
                var b = m.AddFolder("/B/Shared/");
                b.Id = folderId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Select(f => f.Path).ShouldContain("/B/Shared/");
            model.SolutionFolders.Select(f => f.Path).ShouldNotContain("/A/Shared/");
        }

        [Fact]
        public void WhenNestedFolderRenamed_ParentUnaffected_ShouldRenameOnlyThatFolder()
        {
            var parentId = Guid.NewGuid();
            var childId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var parent = m.AddFolder("/Database/");
                parent.Id = parentId;
                var child = m.AddFolder("/Database/Infrastructure/");
                child.Id = childId;
            });

            var existing = Build(m =>
            {
                m.AddFolder("/Database/");
                m.AddFolder("/Database/Infrastructure/");
            });

            var generated = Build(m =>
            {
                var parent = m.AddFolder("/Database/");
                parent.Id = parentId;
                var child = m.AddFolder("/Database/Persistence/");
                child.Id = childId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Select(f => f.Path).ShouldBe(["/Database/", "/Database/Persistence/"], ignoreOrder: true);
        }

        [Fact]
        public void WhenParentFolderRenamed_ChildFolderShouldCascadeCorrectly()
        {
            var parentId = Guid.NewGuid();
            var childId = Guid.NewGuid();
            var projectId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var parent = m.AddFolder("/Database/");
                parent.Id = parentId;
                var child = m.AddFolder("/Database/Infrastructure/");
                child.Id = childId;
                var p = m.AddProject("Infrastructure/MyApp.Migrations/MyApp.Migrations.csproj", null, child);
                p.Id = projectId;
            });

            var existing = Build(m =>
            {
                m.AddFolder("/Database/");
                var child = m.AddFolder("/Database/Infrastructure/");
                m.AddProject("Infrastructure/MyApp.Migrations/MyApp.Migrations.csproj", null, child);
            });

            // Parent renamed, child's own name unchanged
            var generated = Build(m =>
            {
                var parent = m.AddFolder("/Persistence/");
                parent.Id = parentId;
                var child = m.AddFolder("/Persistence/Infrastructure/");
                child.Id = childId;
                var p = m.AddProject("Infrastructure/MyApp.Migrations/MyApp.Migrations.csproj", null, child);
                p.Id = projectId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Select(f => f.Path).ShouldBe(["/Persistence/", "/Persistence/Infrastructure/"], ignoreOrder: true);
            model.SolutionProjects.Single().Parent!.Path.ShouldBe("/Persistence/Infrastructure/");
        }

        [Fact]
        public void WhenFolderRenamed_ButUserAlreadyHandRenamedIt_ShouldBackOffAndInsertFreshFolder()
        {
            var folderId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                folder.Id = folderId;
            });

            // User already hand-renamed the folder directly in the file
            var existing = Build(m => m.AddFolder("/3 - Domain Hand-Renamed/"));

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Core/");
                folder.Id = folderId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Select(f => f.Path).ShouldBe(["/3 - Domain Hand-Renamed/", "/3 - Core/"], ignoreOrder: true);
        }

        [Fact]
        public void WhenTwoFoldersSwapNames_ShouldNotCrossWireIdentities()
        {
            var idA = Guid.NewGuid();
            var idB = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var a = m.AddFolder("/Foo/");
                a.Id = idA;
                var b = m.AddFolder("/Bar/");
                b.Id = idB;
            });

            var existing = Build(m =>
            {
                m.AddFolder("/Foo/");
                m.AddFolder("/Bar/");
            });

            var generated = Build(m =>
            {
                var a = m.AddFolder("/Bar/");
                a.Id = idA;
                var b = m.AddFolder("/Foo/");
                b.Id = idB;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Count().ShouldBe(2, "the swap must not collapse or duplicate either folder");
        }

        // ----- Preservation of manual content -----

        [Fact]
        public void WhenUserManuallyAddedProject_ShouldBePreserved()
        {
            var apiId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = apiId;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                m.AddProject("MyApp.External/MyApp.External.csproj"); // added by hand, never Intent-modelled
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = apiId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldContain("MyApp.External/MyApp.External.csproj");
        }

        [Fact]
        public void WhenUserManuallyAddedFolder_ShouldBePreserved()
        {
            var previousOutput = Build(m => { });
            var existing = Build(m => m.AddFolder("/NewFolder1/"));
            var generated = Build(m => { });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Select(f => f.Path).ShouldContain("/NewFolder1/");
        }

        [Fact]
        public void WhenUserAddedUnrelatedSolutionItems_ShouldSurviveRegardlessOfIntentChanges()
        {
            var apiId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/0 - Solution Items/");
                folder.AddFile("README.md");
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/0 - Solution Items/");
                folder.AddFile("README.md");
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = apiId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            var model = Parse(result.Content);
            model.SolutionFolders.Single(f => f.Path == "/0 - Solution Items/").Files.ShouldContain("README.md");
            model.SolutionProjects.Select(p => p.FilePath.Replace('\\', '/')).ShouldContain("MyApp.Api/MyApp.Api.csproj");
        }

        // ----- Crash / corruption -----

        [Fact]
        public void WhenExistingFileHasDuplicateProjectEntry_ShouldThrowExplainingDuplicate()
        {
            var generated = Build(m => { });
            const string existing = """
                <Solution>
                  <Folder Name="/3 - Domain/">
                    <Project Path="MyApp.Domain/MyApp.Domain.csproj" />
                  </Folder>
                  <Folder Name="/4 - Infrastructure/">
                    <Project Path="MyApp.Domain/MyApp.Domain.csproj" />
                  </Folder>
                </Solution>
                """;

            var ex = Should.Throw<Exception>(() => SlnxMerger.Merge(generated, existing, previousOutput: null));
            ex.Message.ShouldContain("duplicate");
            ex.Message.ShouldContain(Normalized(existing));
        }

        [Fact]
        public void WhenExistingFileIsNotValidXml_ShouldThrowExplainingInvalidXml()
        {
            var generated = Build(m => { });
            const string existing = """
                <Solution>
                  <Folder Name="/3 - Domain/">
                    <Project Path="MyApp.Domain/MyApp.Domain.csproj" />
                  </Folder>
                """; // missing closing </Solution> - not well-formed XML

            var ex = Should.Throw<Exception>(() => SlnxMerger.Merge(generated, existing, previousOutput: null));
            ex.Message.ShouldContain("not valid XML");
            ex.Message.ShouldContain(Normalized(existing));
        }

        [Fact]
        public void WhenExistingFileIsWellFormedXmlButNotASolution_ShouldThrowWithLibraryMessage()
        {
            var generated = Build(m => { });
            const string existing = """
                <NotASolution>
                </NotASolution>
                """;

            var ex = Should.Throw<Exception>(() => SlnxMerger.Merge(generated, existing, previousOutput: null));
            ex.Message.ShouldContain("Not a solution file");
            ex.Message.ShouldNotContain("duplicate");
            ex.Message.ShouldContain(Normalized(existing));
        }

        // ----- Output guarantee -----

        [Fact]
        public void WhenExistingFileAlreadyHasAStrayIdAttribute_ShouldNeverSurviveToOutput()
        {
            // Defence in depth: even if Existing itself already carries an Id attribute from some
            // other source (e.g. a leftover from a different module version), the final output is
            // always rebuilt fresh rather than serializing Existing directly, so a stray Id can
            // never leak through untouched.
            var untouchedId = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = untouchedId;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = untouchedId; // stray Id already present on disk, from some other source
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/1 - Api/");
                var p = m.AddProject("MyApp.Api/MyApp.Api.csproj", null, folder);
                p.Id = untouchedId;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            result.Content.ShouldNotContain("Id=");
        }

        [Fact]
        public void Merge_NeverProducesIdAttributeInOutput_AcrossRenameMoveAndInsertScenarios()
        {
            var idA = Guid.NewGuid();
            var idB = Guid.NewGuid();

            var previousOutput = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                var a = m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
                a.Id = idA;
            });

            var existing = Build(m =>
            {
                var folder = m.AddFolder("/3 - Domain/");
                m.AddProject("MyApp.Domain/MyApp.Domain.csproj", null, folder);
            });

            var generated = Build(m =>
            {
                var folder = m.AddFolder("/3 - Core/");
                var a = m.AddProject("MyApp.Core/MyApp.Core.csproj", null, folder);
                a.Id = idA;
                var b = m.AddProject("MyApp.New/MyApp.New.csproj", null, folder);
                b.Id = idB;
            });

            var result = SlnxMerger.Merge(generated, existing, previousOutput);

            result.Content.ShouldNotContain("Id=");
        }

        // ----- Helpers -----

        private static string Normalized(string content) =>
            content.Replace("\r\n", "\n");

        private static string Build(Action<SolutionModel> configure)
        {
            var model = new SolutionModel();
            configure(model);
            return Serialize(model);
        }

        private static string Serialize(SolutionModel model)
        {
            using var stream = new MemoryStream();
            SolutionSerializers.SlnXml.SaveAsync(stream, model, CancellationToken.None).GetAwaiter().GetResult();
            stream.Position = 0;
            return new StreamReader(stream).ReadToEnd();
        }

        private static SolutionModel Parse(string content)
        {
            using var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(content));
            return SolutionSerializers.SlnXml.OpenAsync(stream, CancellationToken.None).GetAwaiter().GetResult();
        }
    }
}
