// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Security.JWT.Templates.CurrentUserService
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.Application.Identity.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\CurrentUserService\CurrentUserServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class CurrentUserServiceTemplate : CSharpTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System.Security.Claims;\r\nusing System.Threading.Tasks;\r\nusing IdentityModel;\r\nusing Microsoft.AspNetCore.Authorization;\r\nusing Microsoft.AspNetCore.Http;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\CurrentUserService\CurrentUserServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\CurrentUserService\CurrentUserServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\CurrentUserService\CurrentUserServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetCurrentUserServiceInterfaceName()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly ClaimsPrincipal _claimsPrincipal;\r\n        private readonly IAuthorizationService _authorizationService;\r\n\r\n        public ");
            
            #line 26 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\CurrentUserService\CurrentUserServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(IHttpContextAccessor httpContextAccessor, IAuthorizationService authorizationService)\r\n        {\r\n            _claimsPrincipal = httpContextAccessor?.HttpContext?.User;\r\n            _authorizationService = authorizationService;\r\n        }\r\n\r\n        public string UserId => _claimsPrincipal?.FindFirst(JwtClaimTypes.Subject)?.Value;\r\n\r\n        public string UserName => _claimsPrincipal?.FindFirst(JwtClaimTypes.Name)?.Value;\r\n\r\n        public async Task<bool> AuthorizeAsync(string policy)\r\n        {\r\n            return (await _authorizationService.AuthorizeAsync(_claimsPrincipal, policy)).Succeeded;\r\n        }\r\n\r\n        public async Task<bool> IsInRoleAsync(string role)\r\n        {\r\n            return await Task.FromResult(_claimsPrincipal?.IsInRole(role) ?? false);\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
