// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.AspNetCore.Swashbuckle.Templates.SwashbuckleConfiguration
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.AspNetCore.Swashbuckle.Templates.AuthorizeCheckOperationFilter;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Swashbuckle\Templates\SwashbuckleConfiguration\SwashbuckleConfigurationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SwashbuckleConfigurationTemplate : CSharpTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using Microsoft.AspNetCore.Builder;\r\nusing Microsoft.Extensions.Configuration;\r\nusing Microsoft.Extensions.DependencyInjection;\r\nusing Microsoft.OpenApi.Models;\r\nusing Swashbuckle.AspNetCore.SwaggerUI;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Swashbuckle\Templates\SwashbuckleConfiguration\SwashbuckleConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public static class ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Swashbuckle\Templates\SwashbuckleConfiguration\SwashbuckleConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public static IServiceCollection ConfigureSwagger(this IServiceCollection services, IConfiguration configuration)\r\n        {\r\n            services.AddSwaggerGen(options =>\r\n            {\r\n                options.SwaggerDoc(\"v1\", new OpenApiInfo\r\n                {\r\n                    Version = \"v1\",\r\n                    Title = \"");
            
            #line 30 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Swashbuckle\Templates\SwashbuckleConfiguration\SwashbuckleConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputTarget.ApplicationName()));
            
            #line default
            #line hidden
            this.Write(" API\"\r\n                });\r\n                options.OperationFilter<");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Swashbuckle\Templates\SwashbuckleConfiguration\SwashbuckleConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(AuthorizeCheckOperationFilterTemplate.TemplateId)));
            
            #line default
            #line hidden
            this.Write(">();\r\n            });\r\n\r\n            return services;\r\n        }\r\n\r\n        public static void UseSwashbuckle(this IApplicationBuilder app)\r\n        {\r\n            app.UseSwagger(options =>\r\n            {\r\n                options.RouteTemplate = \"swagger/{documentName}/swagger.json\";\r\n            });\r\n            app.UseSwaggerUI(options =>\r\n            {\r\n                options.RoutePrefix = \"swagger\";\r\n                options.ConfigObject = new ConfigObject()\r\n                {\r\n                    Urls = new[]\r\n                    {\r\n                        new UrlDescriptor() { Url = \"/swagger/v1/swagger.json\", Name = \"");
            
            #line 51 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Swashbuckle\Templates\SwashbuckleConfiguration\SwashbuckleConfigurationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputTarget.ApplicationName()));
            
            #line default
            #line hidden
            this.Write(" API V1\" }\r\n                    }\r\n                };\r\n                options.EnableDeepLinking();\r\n                options.DisplayOperationId();\r\n                options.DefaultModelsExpandDepth(-1);\r\n                options.DefaultModelsExpandDepth(2);\r\n                options.DefaultModelRendering(ModelRendering.Model);\r\n                options.DocExpansion(DocExpansion.List);\r\n                options.ShowExtensions();\r\n                options.EnableFilter(\"\");\r\n            });\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
