// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Application.ServiceImplementations.FluentValidation.Templates.ValidationProvider
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.Application.FluentValidation.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.ServiceImplementations.FluentValidation\Templates\ValidationProvider\ValidationProviderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ValidationProviderTemplate : CSharpTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing System.Threading;\r\nusing System.Threading.Tasks;\r\nusing FluentValidation;\r\nusing Microsoft.Extensions.DependencyInjection;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.ServiceImplementations.FluentValidation\Templates\ValidationProvider\ValidationProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 23 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.ServiceImplementations.FluentValidation\Templates\ValidationProvider\ValidationProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly IServiceProvider _serviceProvider;\r\n\r\n        public ");
            
            #line 27 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.ServiceImplementations.FluentValidation\Templates\ValidationProvider\ValidationProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(IServiceProvider serviceProvider)\r\n        {\r\n            _serviceProvider = serviceProvider;\r\n        }\r\n\r\n        public async Task Handle<TRequest>(TRequest request, CancellationToken cancellationToken = default)\r\n        {\r\n            var validationBehaviour = _serviceProvider.GetService<");
            
            #line 34 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.ServiceImplementations.FluentValidation\Templates\ValidationProvider\ValidationProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetValidationBehaviourName()));
            
            #line default
            #line hidden
            this.Write("<TRequest>>();\r\n            await validationBehaviour.Handle(request, cancellationToken);\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
