<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1701,1702</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Subscribe.MassTransit.DomainInteractionsRepro.Domain\Subscribe.MassTransit.DomainInteractionsRepro.Domain.csproj" />
    <ProjectReference Include="..\Subscribe.MassTransit.DomainInteractionsRepro.Application\Subscribe.MassTransit.DomainInteractionsRepro.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12" />
  </ItemGroup>
  </Project>