using Intent.RoslynWeaver.Attributes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlDbProject.Domain.Entities.PK;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.EntityFrameworkCore.EntityTypeConfiguration", Version = "1.0")]

namespace SqlDbProject.Infrastructure.Persistence.Configurations.PK
{
    public class AutoGeneratedKeyConfiguration : IEntityTypeConfiguration<AutoGeneratedKey>
    {
        public void Configure(EntityTypeBuilder<AutoGeneratedKey> builder)
        {
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id)
                .HasDefaultValueSql("NEWSEQUENTIALID()");

            builder.Property(x => x.Name)
                .IsRequired();

            builder.Property(x => x.Value)
                .IsRequired();

            builder.Ignore(e => e.DomainEvents);
        }
    }
}