// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Application.Contracts.Clients.Templates.DtoContract
{
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Modules.Common.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DtoContractTemplate : CSharpTemplateBase<Intent.Modelers.Types.ServiceProxies.Api.ServiceProxyDTOModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System.Collections.Generic;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]" +
                    "\r\n\r\nnamespace ");
            
            #line 9 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 11 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 11 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenericTypes));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public static ");
            
            #line 13 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 13 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenericTypes));
            
            #line default
            #line hidden
            this.Write(" Create(");
            
            #line 13 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConstructorParameters()));
            
            #line default
            #line hidden
            this.Write(") \r\n        {\r\n            return new ");
            
            #line 15 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 15 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenericTypes));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"

    foreach (var field in Model.Fields)
    {

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLocalVariableName()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 22 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n");
            
            #line 27 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"

    foreach (var field in Model.Fields)
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 31 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(field.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 31 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 32 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Application.Contracts.Clients\Templates\DtoContract\DtoContractTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
