// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.VisualStudio.Projects.Templates.CoreWeb.AppSettings
{
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.VisualStudio;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.VisualStudio.Projects\Templates\CoreWeb\AppSettings\AppSettingsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AppSettingsTemplate : IntentTemplateBase<AppSettingsModel, Intent.Modules.VisualStudio.Projects.Templates.CoreWeb.AppSettings.AppSettingsDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write("{\r\n  \"Logging\": {\r\n    \"LogLevel\": {\r\n      \"Default\": \"Information\" ");
            
            #line 15 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.VisualStudio.Projects\Templates\CoreWeb\AppSettings\AppSettingsTemplate.tt"
if (IncludeAspNetCoreLoggingLevel()) {
            
            #line default
            #line hidden
            this.Write(", \r\n      \"Microsoft.AspNetCore\": \"Warning\"\r\n");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.VisualStudio.Projects\Templates\CoreWeb\AppSettings\AppSettingsTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("    }\r\n  }");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.VisualStudio.Projects\Templates\CoreWeb\AppSettings\AppSettingsTemplate.tt"
if (IncludeAllowHosts()) {
            
            #line default
            #line hidden
            this.Write(", \r\n  \"AllowedHosts\": \"*\"\r\n");
            
            #line 21 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.VisualStudio.Projects\Templates\CoreWeb\AppSettings\AppSettingsTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
