using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EntityFrameworkCore.SqlServer.EF10.Domain.Entities.PkDataSources;
using Intent.RoslynWeaver.Attributes;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.Entities.Repositories.Api.EntityRepositoryInterface", Version = "1.0")]

namespace EntityFrameworkCore.SqlServer.EF10.Domain.Repositories.PkDataSources
{
    [IntentManaged(Mode.Merge, Signature = Mode.Fully)]
    public interface ICompKeyAutoGeneratedDataSourceEntityRepository : IEFRepository<CompKeyAutoGeneratedDataSourceEntity, CompKeyAutoGeneratedDataSourceEntity>
    {
        [IntentManaged(Mode.Fully)]
        Task<CompKeyAutoGeneratedDataSourceEntity?> FindByIdAsync((long Id1, long Id2) id, CancellationToken cancellationToken = default);
        [IntentManaged(Mode.Fully)]
        Task<CompKeyAutoGeneratedDataSourceEntity?> FindByIdAsync((long Id1, long Id2) id, Func<IQueryable<CompKeyAutoGeneratedDataSourceEntity>, IQueryable<CompKeyAutoGeneratedDataSourceEntity>> queryOptions, CancellationToken cancellationToken = default);
    }
}