// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.AspNetCore.Controllers.Interop.EntityFrameworkCore.Templates.DbInitializationExtensions
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.EntityFrameworkCore.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Controllers.Interop.EntityFrameworkCore\Templates\DbInitializationExtensions\DbInitializationExtensionsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DbInitializationExtensionsTemplate : CSharpTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing Microsoft.AspNetCore.Builder;\r\nusing Microsoft.Extensions.DependencyInjection;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Controllers.Interop.EntityFrameworkCore\Templates\DbInitializationExtensions\DbInitializationExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public static class ");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Controllers.Interop.EntityFrameworkCore\Templates\DbInitializationExtensions\DbInitializationExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        /// <summary>\r\n        /// If configured to do so, a check is performed to see\r\n        /// whether the database exist and if not will create it\r\n        /// based on this container configuration.\r\n        /// </summary>\r\n        public static void EnsureDbCreation(this IApplicationBuilder builder)\r\n        {\r\n            using var scope = builder.ApplicationServices.CreateScope();\r\n            var dbContext = scope.ServiceProvider.GetService<");
            
            #line 29 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.AspNetCore.Controllers.Interop.EntityFrameworkCore\Templates\DbInitializationExtensions\DbInitializationExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetDbContextName()));
            
            #line default
            #line hidden
            this.Write(">();\r\n            if (dbContext == null)\r\n            {\r\n                throw new InvalidOperationException(\"DbContext not configured in Services Collection in order to ensure that the database is created.\");\r\n            }\r\n\r\n            dbContext.EnsureDbCreated();\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
