// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Eventing.MassTransit.Templates.MassTransitEventBus
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.Eventing.Contracts.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Eventing.MassTransit\Templates\MassTransitEventBus\MassTransitEventBusTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MassTransitEventBusTemplate : CSharpTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Threading;\r\nusing System.Threading.Tasks;\r\nusing MassTransit;\r\nusing Microsoft.Extensions.DependencyInjection;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 20 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Eventing.MassTransit\Templates\MassTransitEventBus\MassTransitEventBusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 22 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Eventing.MassTransit\Templates\MassTransitEventBus\MassTransitEventBusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 22 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Eventing.MassTransit\Templates\MassTransitEventBus\MassTransitEventBusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetEventBusInterfaceName()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly IServiceProvider _serviceProvider;\r\n        private readonly List<object> _messagesToPublish = new();\r\n\r\n        public ");
            
            #line 27 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Eventing.MassTransit\Templates\MassTransitEventBus\MassTransitEventBusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(IServiceProvider serviceProvider)\r\n        {\r\n            _serviceProvider = serviceProvider;\r\n        }\r\n\r\n        public ConsumeContext? ConsumeContext { get; set; }\r\n        \r\n        public void Publish<T>(T message) where T : class\r\n        {\r\n            _messagesToPublish.Add(message);\r\n        }\r\n\r\n        public async Task FlushAllAsync(CancellationToken cancellationToken = default)\r\n        {\r\n            await PublishWithNormalContext(cancellationToken);\r\n            \r\n            _messagesToPublish.Clear();\r\n        }\r\n\r\n        private async Task PublishWithNormalContext(CancellationToken cancellationToken)\r\n        {\r\n            var publishEndpoint = _serviceProvider.GetRequiredService<IPublishEndpoint>();\r\n            var messageScheduler = _serviceProvider.GetRequiredService<IMessageScheduler>();\r\n            \r\n            await publishEndpoint.PublishBatch(_messagesToPublish, cancellationToken).ConfigureAwait(false);\r\n            \r\n            foreach (var scheduleEntry in _messagesToSchedule)\r\n            {\r\n                await messageScheduler.SchedulePublish(scheduleEntry.Scheduled, scheduleEntry.Message, cancellationToken).ConfigureAwait(false);\r\n            }\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
