<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1701,1702</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WolverineEventing.Outbox.SqlServer.Subscribe.Domain\WolverineEventing.Outbox.SqlServer.Subscribe.Domain.csproj" />
    <ProjectReference Include="..\WolverineEventing.Outbox.SqlServer.Subscribe.Application\WolverineEventing.Outbox.SqlServer.Subscribe.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9" />
    <PackageReference Include="WolverineFx" Version="5.39.5" />
    <PackageReference Include="WolverineFx.AzureServiceBus" Version="5.39.5" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="5.39.5" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="5.39.5" />
    <PackageReference Include="WolverineFx.SqlServer" Version="5.39.5" />
  </ItemGroup>
  </Project>