using EntityFrameworkCore.SqlServer.EF10.Domain.Entities.PkDataSources;
using Intent.RoslynWeaver.Attributes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.EntityFrameworkCore.EntityTypeConfiguration", Version = "1.0")]

namespace EntityFrameworkCore.SqlServer.EF10.Infrastructure.Persistence.Configurations.PkDataSources
{
    public class CompKeyAutoGeneratedDataSourceEntityConfiguration : IEntityTypeConfiguration<CompKeyAutoGeneratedDataSourceEntity>
    {
        public void Configure(EntityTypeBuilder<CompKeyAutoGeneratedDataSourceEntity> builder)
        {
            builder.HasKey(x => new { x.Id1, x.Id2 });

            builder.Property(x => x.Id1)
                .ValueGeneratedOnAdd();

            builder.Property(x => x.Id2)
                .ValueGeneratedOnAdd();

            builder.Property(x => x.FieldValue)
                .IsRequired();
        }
    }
}