namespace Intent.Modules.Constants;

// Would love for this file to be generated by Intent since the roles are specified in the imodspec file
public static class Roles
{
    public static class Distribution
    {
        public const string WebApi = "Distribution.WebApi";
    }

    public static class Application
    {
        public const string ContractDto = "Application.Contract.Dto";
    }

    public static class Domain
    {
        public const string EntityInterface = "Domain.Entity.Interface";
    }

    public static class Repository
    {
        public const string InterfacePagedResult = "Repository.Interface.PagedResult";
    }
}