<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1701,1702</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WolverineEventing.Subscribe.RabbitMQ.Domain\WolverineEventing.Subscribe.RabbitMQ.Domain.csproj" />
    <ProjectReference Include="..\WolverineEventing.Subscribe.RabbitMQ.Application\WolverineEventing.Subscribe.RabbitMQ.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9" />
    <PackageReference Include="WolverineFx" Version="5.39.5" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="5.39.5" />
  </ItemGroup>
  </Project>