<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="3.10.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wolverine.Publish.RabbitMQ\Wolverine.Publish.RabbitMQ.Infrastructure\Wolverine.Publish.RabbitMQ.Infrastructure.csproj" />
    <ProjectReference Include="..\Wolverine.Subscribe.RabbitMQ\Wolverine.Subscribe.RabbitMQ.Infrastructure\Wolverine.Subscribe.RabbitMQ.Infrastructure.csproj" Aliases="Sub" />
    <ProjectReference Include="..\Wolverine.Subscribe.RabbitMQ\Wolverine.Subscribe.RabbitMQ.Application\Wolverine.Subscribe.RabbitMQ.Application.csproj" Aliases="Sub" />
    <ProjectReference Include="..\Wolverine.Subscribe.RabbitMQ\Wolverine.Subscribe.RabbitMQ.Domain\Wolverine.Subscribe.RabbitMQ.Domain.csproj" Aliases="Sub" />
  </ItemGroup>

</Project>
