<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1701,1702</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wolverine.CQRS.TestApplication.Domain\Wolverine.CQRS.TestApplication.Domain.csproj" />
    <ProjectReference Include="..\Wolverine.CQRS.TestApplication.Application\Wolverine.CQRS.TestApplication.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12" />
    <PackageReference Include="WolverineFx" Version="5.39.5" />
  </ItemGroup>
  </Project>
