<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>1701,1702</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AwsLambdaFunction.Sqs.GroupA.Application\AwsLambdaFunction.Sqs.GroupA.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="3.0.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.3" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.3" />
  </ItemGroup>
  </Project>