// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Integration.HttpClients.Templates.HttpClient
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.Application.Contracts.Clients.Templates;
    using Intent.Metadata.WebApi.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class HttpClientTemplate : CSharpTemplateBase<Intent.Modelers.Types.ServiceProxies.Api.ServiceProxyModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.IO;\r\nusing System.Linq;\r\nusing System.Net;\r\nusing System.Net.Http;\r\nusing System.Net.Http.Headers;\r\nusing System.Text;\r\nusing System.Text.Json;\r\nusing System.Threading;\r\nusing System.Threading.Tasks;\r\nusing Microsoft.AspNetCore.WebUtilities;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 27 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 29 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 29 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetServiceContractName()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly HttpClient _httpClient;\r\n\r\n        private readonly JsonSerializerOptions _serializerOptions = new JsonSerializerOptions()\r\n        {\r\n            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,\r\n        };\r\n\r\n        public ");
            
            #line 38 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(HttpClient httpClient)\r\n        {\r\n            _httpClient = httpClient;\r\n        }\r\n\r\n");
            
            #line 43 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

    foreach (var operation in Model.MappedService.Operations.Where(p => p.HasHttpSettings()))
    {

            
            #line default
            #line hidden
            this.Write("        public async ");
            
            #line 47 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnType(operation)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 47 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationName(operation)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 47 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {");
            
            #line 48 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        // We're leveraging the C# $"" notation to actually take leverage of the parameters
        // that are meant to be Route-based.

            
            #line default
            #line hidden
            this.Write("            var relativeUri = $\"");
            
            #line 52 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRelativeUri(operation)));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 53 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        if (HasQueryParameter(operation))
        {

            
            #line default
            #line hidden
            this.Write("            \r\n            var queryParams = new Dictionary<string, string>();\r\n");
            
            #line 59 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            foreach (var queryParameter in GetQueryParameters(operation))
            {

            
            #line default
            #line hidden
            this.Write("            queryParams.Add(\"");
            
            #line 63 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParameter.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 63 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParameterValueExpression(queryParameter)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 64 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("            relativeUri = QueryHelpers.AddQueryString(relativeUri, queryParams);\r\n\r\n");
            
            #line 69 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("            var request = new HttpRequestMessage(");
            
            #line 72 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHttpVerb(operation)));
            
            #line default
            #line hidden
            this.Write(", relativeUri);\r\n            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(\"application/json\"));\r\n");
            
            #line 74 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        foreach (var headerParameter in GetHeaderParameters(operation))
        {

            
            #line default
            #line hidden
            this.Write("            request.Headers.Add(\"");
            
            #line 78 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headerParameter.HeaderName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 78 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headerParameter.Parameter.Name.ToParameterName()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 80 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        }

        if (HasBodyParameter(operation))
        {

            
            #line default
            #line hidden
            this.Write("            \r\n            var content = JsonSerializer.Serialize(");
            
            #line 87 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBodyParameterName(operation)));
            
            #line default
            #line hidden
            this.Write(", _serializerOptions);\r\n            request.Content = new StringContent(content, Encoding.Default, \"application/json\");\r\n\r\n");
            
            #line 90 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        }
        else if (HasFormUrlEncodedParameter(operation))
        {

            
            #line default
            #line hidden
            this.Write("            \r\n            var formVariables = new List<KeyValuePair<string, string>>();\r\n");
            
            #line 97 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            foreach (var formParameter in GetFormUrlEncodedParameters(operation))
            {

            
            #line default
            #line hidden
            this.Write("            formVariables.Add(new KeyValuePair<string, string>(\"");
            
            #line 101 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(formParameter.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 101 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParameterValueExpression(formParameter)));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 102 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("            var content = new FormUrlEncodedContent(formVariables);\r\n            request.Content = content;\r\n");
            
            #line 107 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("            \r\n            using (var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false))\r\n            {\r\n                if (!response.IsSuccessStatusCode)\r\n                {\r\n                    throw await ");
            
            #line 115 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetHttpClientRequestExceptionName()));
            
            #line default
            #line hidden
            this.Write(".Create(_httpClient.BaseAddress, request, response, cancellationToken).ConfigureAwait(false);\r\n                }\r\n");
            
            #line 117 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        if (HasResponseType(operation))
        {

            
            #line default
            #line hidden
            this.Write("                if (response.StatusCode == HttpStatusCode.NoContent || response.Content.Headers.ContentLength == 0)\r\n                {\r\n                    return default;\r\n                }\r\n\r\n                using (var contentStream = await response.Content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(false))\r\n                {\r\n");
            
            #line 128 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            if (HasWrappedReturnType(operation))
            {

            
            #line default
            #line hidden
            this.Write("                    var wrappedObj = await JsonSerializer.DeserializeAsync<");
            
            #line 132 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetJsonResponseName()));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 132 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(operation.ReturnType)));
            
            #line default
            #line hidden
            this.Write(">>(contentStream, _serializerOptions, cancellationToken).ConfigureAwait(false);\r\n                    return wrappedObj.Value;\r\n");
            
            #line 134 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
   
            }
            else if (operation.ReturnType.HasStringType() && !operation.ReturnType.IsCollection)
            {

            
            #line default
            #line hidden
            this.Write("                    var str = await new StreamReader(contentStream).ReadToEndAsync().ConfigureAwait(false);\r\n                    if (str.StartsWith(@\"\"\"\") || str.StartsWith(\"'\")) { str = str.Substring(1, str.Length - 2); }\r\n                    return str;\r\n");
            
            #line 142 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            }
            else if (IsReturnTypePrimitive(operation))
            {

            
            #line default
            #line hidden
            this.Write("                    var str = await new StreamReader(contentStream).ReadToEndAsync().ConfigureAwait(false);\r\n                    if (str.StartsWith(@\"\"\"\") || str.StartsWith(\"'\")) { str = str.Substring(1, str.Length - 2); }\r\n                    return ");
            
            #line 149 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(operation.ReturnType)));
            
            #line default
            #line hidden
            this.Write(".Parse(str);\r\n");
            
            #line 150 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
              
            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                    return await JsonSerializer.DeserializeAsync<");
            
            #line 155 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(operation.ReturnType)));
            
            #line default
            #line hidden
            this.Write(">(contentStream, _serializerOptions, cancellationToken).ConfigureAwait(false);\r\n");
            
            #line 156 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("                }\r\n");
            
            #line 160 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n");
            
            #line 165 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Integration.HttpClients\Templates\HttpClient\HttpClientTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        public void Dispose()\r\n        {\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
