// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Security.JWT.Templates.ConfigurationJWTAuthentication
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\ConfigurationJWTAuthentication\ConfigurationJWTAuthenticationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ConfigurationJWTAuthenticationTemplate : CSharpTemplateBase<object, Intent.Modules.Security.JWT.Templates.ConfigurationJWTAuthentication.JWTAuthenticationDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing Microsoft.Extensions.Conf" +
                    "iguration;\r\nusing Microsoft.Extensions.DependencyInjection;\r\n\r\n[assembly: Defaul" +
                    "tIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 17 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\ConfigurationJWTAuthentication\ConfigurationJWTAuthenticationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public static class ");
            
            #line 19 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\ConfigurationJWTAuthentication\ConfigurationJWTAuthenticationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"
    {
        // Use '[IntentManaged(Mode.Ignore)]' on this method should you want to deviate from the standard JWT token approach
        public static IServiceCollection ConfigureJWTAuthentication(this IServiceCollection services, IConfiguration configuration)
        {
            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
            ");
            
            #line 25 "C:\Dev\Intent.Modules.NET\Modules\Intent.Modules.Security.JWT\Templates\ConfigurationJWTAuthentication\ConfigurationJWTAuthenticationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(base.GetDecoratorsOutput(p => p.GetConfigurationCode())));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            return services;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
